name: Release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2022

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FIREBASE_CLIENT_EMAIL: ""
      FIREBASE_KEY_ID: ""
      FIREBASE_PROJECT_ID: ""
      GH_ISSUES_CLIENT_ID: ""

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.10"

      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Show versions
        shell: bash
        run: |
          node --version
          npm --version
          python --version

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Publish dry-run
        env:
          GH_PUBLISH_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_CLIENT_EMAIL: ""
          FIREBASE_KEY_ID: ""
          FIREBASE_PROJECT_ID: ""
          GH_ISSUES_CLIENT_ID: ""
        run: npm run publish -- --dry-run

      - name: Publish release
        env:
          GH_PUBLISH_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FIREBASE_CLIENT_EMAIL: ""
          FIREBASE_KEY_ID: ""
          FIREBASE_PROJECT_ID: ""
          GH_ISSUES_CLIENT_ID: ""
        run: npm run publish -- --from-dry-run
